// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Me from "@/components/Me"; // ← 로그인 위젯

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* 헤더 + 로그인 위젯 */}
        <header style={{ borderBottom: "1px solid #eee", background: "#fff" }}>
          <div style={{
            maxWidth: 900, margin: "0 auto", padding: "12px 16px",
            display: "flex", alignItems: "center", justifyContent: "space-between"
          }}>
            <div style={{ fontWeight: 600 }}>Campus Market</div>
            <Me /> {/* ← 여기서 로그인/로그아웃 보임 */}
          </div>
        </header>

        {/* 본문 */}
        <main style={{ maxWidth: 900, margin: "0 auto", padding: "16px" }}>
          {children}
        </main>
      </body>
    </html>
  );
}